language: node_js
node_js:
  - 8.10.0
services:
  - docker
before_install:
  # Install terraform.
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  # Install AWS CLI.
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  # Set branch from travis build env var.
  - export BRANCH=$TRAVIS_BRANCH
  # Get env file for the current branch from s3.
  - yarn get-env
cache:
  directories:
    - "$HOME/.yarn-cache"
install:
  - yarn install --frozen-lockfile
script:
  - yarn build
  - yarn package
  - yarn plan
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn deploy
    on:
      branch: production
