variable "domain"                       { }
variable "app_package"                  { }
variable "twitter_consumer_key"         { }
variable "twitter_consumer_secret"      { }
variable "twitter_access_token"         { }
variable "twitter_access_token_secret"  { }
variable "ga_tracking_id"               { }
variable "name"                         { }
variable "description"                  { }
variable "email"                        { }
variable "github_username"              { }
variable "twitter_username"             { }
variable "medium_username"              { }
variable "linkedin_username"            { }
variable "linkedin_position"            { }
variable "mailgun_smtp_password"        { }