variable app_package {}
variable node_env {}
variable render_interval {}
variable domain {}
variable twitter_consumer_key {}
variable twitter_consumer_secret {}
variable twitter_access_token {}
variable twitter_access_token_secret {}
variable ga_tracking_id {}
variable ssl_certificate_arn {}
